# Generated by Django 4.0.4 on 2022-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_order_products_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='product.product', verbose_name='Продукт'),
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
    ]
